-- Add updated_at columns required for offline-lite incremental synchronization.
-- MySQL 8+

ALTER TABLE expenses
ADD COLUMN updated_at DATETIME
NOT NULL DEFAULT CURRENT_TIMESTAMP
ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE categories
ADD COLUMN updated_at DATETIME
NOT NULL DEFAULT CURRENT_TIMESTAMP
ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE providers
ADD COLUMN updated_at DATETIME
NOT NULL DEFAULT CURRENT_TIMESTAMP
ON UPDATE CURRENT_TIMESTAMP;

ALTER TABLE sets
ADD COLUMN updated_at DATETIME
NOT NULL DEFAULT CURRENT_TIMESTAMP
ON UPDATE CURRENT_TIMESTAMP;
