export const EXPENSE_TYPES = {
  FIXED: 1,
  VARIABLE: 2,
  PROVIDER: 3
};

export const EXPENSE_TYPE_LABELS = {
  [EXPENSE_TYPES.FIXED]: 'FIJO',
  [EXPENSE_TYPES.VARIABLE]: 'VARIABLE',
  [EXPENSE_TYPES.PROVIDER]: 'PROVEEDOR'
};

export const PAYMENT_METHODS = {
  CASH: 1,
  CREDIT_CARD: 2,
  DEBIT_CARD: 3
};
